sudo: false
language: scala
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
# branches:
#   only:
#     - master
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
script: "mvn test"
notifications:
  email:
    recipients:
      - dang.duong@gmail.com
    on_success: change
    on_failure: change
cache:
  directories:
  - $HOME/.m2
