#!/bin/bash
set -e
# Performs both normal sequential extraction and distributed extraction and compares the outputs.
TMPDIR=$(mktemp -d)
./run-par-extraction $TMPDIR || exit 1

THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_FILE=$TMPDIR/config.properties
SPARK_CONF_FILE=$THISDIR/extraction/src/test/resources/dist-config.properties

cp $THISDIR/extraction/src/test/resources/config.properties $TMPDIR
eval "sed -i 's|base\-dir\=.*|base\-dir\=$THISDIR/extraction/src/test/resources/data|g' $CONFIG_FILE"
eval "sed -i 's|mappings\=.*|mappings\=$THISDIR/extraction/src/test/resources/data/mappings|g' $CONFIG_FILE"
eval "sed -i 's|ontology\=.*|ontology\=$THISDIR/extraction/src/test/resources/data/ontology.xml|g' $CONFIG_FILE"

echo "===================================================================="
echo "Running sequential extraction"
echo "===================================================================="
./run seq-extraction $CONFIG_FILE
mkdir -p $TMPDIR/dbpedia-test-seq-extraction
mv `grep base-dir $CONFIG_FILE | sed -ne 's/^base-dir=//p'`/*wiki/*/*wiki*.gz $TMPDIR/dbpedia-test-seq-extraction

echo "===================================================================="
echo "Computing diffs:"
echo "===================================================================="

diffs=$(diff <(gzip -dc $TMPDIR/dbpedia-test-seq-extraction/*.gz | grep -v "^#" | sort) <(gzip -dc $TMPDIR/dbpedia-test-par-extraction/grouped/*wiki*.gz/part*.gz | grep -v "^#" | sort))

if [ -z "$diffs" ]; then
   echo "Outputs match!"
   exit 0
else
   echo "Outputs not match!"
   exit 1
fi
